[package]
name = "otp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.35" }
data-encoding = "2.5.0"
hmac = "0.12.1"
sha1 = "0.10.6"
wasm-bindgen = "0.2.92"
